const ACTIONS = {
  ADD_TODO: 'ADD_TODO',
  START_EDIT_TODO: 'START_EDIT_TODO',
  END_EDIT_TODO: 'END_EDIT_TODO',
  DELETE_TODO: 'DELETE_TODO',
  COMPLETE_TODO: 'COMPLETE_TODO',
};

export default ACTIONS;
